apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: application
  labels:
    app: my-app
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30002
  selector:
    app: my-app
